export const mockUsers = [
  { id: "u1", name: "Sarah Chen", email: "sarah.chen@school.edu", role: "admin" },
  { id: "u2", name: "James Wilson", email: "james.wilson@school.edu", role: "organizer" },
  { id: "u3", name: "Emily Parker", email: "emily.parker@school.edu", role: "student" },
]

export const mockActivities = [
  {
    id: "a1",
    title: "Basketball Tournament",
    description: "Annual inter-school basketball tournament with teams from 8 schools competing for the championship trophy.",
    category: "sports",
    status: "upcoming",
    approvalStatus: "approved",
    date: "2026-03-15",
    time: "14:00",
    location: "Main Gymnasium",
    capacity: 60,
    enrolled: 42,
    instructor: "James Wilson",
    instructorId: "t1",
  },
  {
    id: "a2",
    title: "Science Fair",
    description: "Students showcase their research projects covering topics from biology to astrophysics.",
    category: "academic",
    status: "ongoing",
    approvalStatus: "approved",
    date: "2026-03-10",
    time: "09:00",
    location: "Science Building",
    capacity: 80,
    enrolled: 65,
    instructor: "Dr. Maria Lopez",
    instructorId: "t2",
  },
  {
    id: "a3",
    title: "Drama Club Performance",
    description: "Spring theatrical performance of Shakespeare's A Midsummer Night's Dream.",
    category: "cultural",
    status: "upcoming",
    approvalStatus: "approved",
    date: "2026-03-20",
    time: "18:00",
    location: "Auditorium",
    capacity: 150,
    enrolled: 98,
    instructor: "Ms. Rachel Green",
    instructorId: "t3",
  },
  {
    id: "a4",
    title: "Coding Hackathon",
    description: "48-hour coding challenge where students build innovative web and mobile applications.",
    category: "technology",
    status: "upcoming",
    approvalStatus: "approved",
    date: "2026-03-25",
    time: "10:00",
    location: "Computer Lab A",
    capacity: 40,
    enrolled: 38,
    instructor: "Prof. Alan Turing",
    instructorId: "t4",
  },
  {
    id: "a5",
    title: "Community Cleanup Drive",
    description: "Volunteer event to clean up the local park and surrounding neighborhood.",
    category: "community",
    status: "completed",
    approvalStatus: "approved",
    date: "2026-02-28",
    time: "08:00",
    location: "Central Park",
    capacity: 100,
    enrolled: 87,
    instructor: "James Wilson",
    instructorId: "t1",
  },
  {
    id: "a6",
    title: "Math Olympiad Prep",
    description: "Advanced mathematics preparation sessions for the regional Math Olympiad competition.",
    category: "academic",
    status: "ongoing",
    approvalStatus: "approved",
    date: "2026-03-05",
    time: "15:00",
    location: "Room 204",
    capacity: 30,
    enrolled: 24,
    instructor: "Dr. Maria Lopez",
    instructorId: "t2",
  },
  {
    id: "a7",
    title: "Photography Workshop",
    description: "Hands-on workshop covering composition, lighting, and post-processing techniques.",
    category: "cultural",
    status: "cancelled",
    approvalStatus: "approved",
    date: "2026-03-12",
    time: "13:00",
    location: "Art Studio",
    capacity: 25,
    enrolled: 12,
    instructor: "Ms. Rachel Green",
    instructorId: "t3",
  },
  {
    id: "a8",
    title: "Robotics Club",
    description: "Build and program robots for the national robotics competition.",
    category: "technology",
    status: "ongoing",
    approvalStatus: "approved",
    date: "2026-03-01",
    time: "16:00",
    location: "Engineering Lab",
    capacity: 20,
    enrolled: 18,
    instructor: "Prof. Alan Turing",
    instructorId: "t4",
  },
  {
    id: "a9",
    title: "Debate Championship Qualifying Round",
    description: "Debate competition for students interested in competitive public speaking and argumentation.",
    category: "academic",
    status: "upcoming",
    approvalStatus: "pending",
    date: "2026-04-10",
    time: "11:00",
    location: "Main Hall",
    capacity: 50,
    enrolled: 0,
    instructor: "James Wilson",
    instructorId: "t1",
  },
  {
    id: "a10",
    title: "Music Festival",
    description: "Student performances featuring various music genres and instruments.",
    category: "cultural",
    status: "upcoming",
    approvalStatus: "pending",
    date: "2026-04-05",
    time: "19:00",
    location: "Auditorium",
    capacity: 200,
    enrolled: 0,
    instructor: "Dr. Maria Lopez",
    instructorId: "t2",
  },
]

export const mockStudents = [
  { id: "s1", name: "Emily Parker", email: "emily.parker@school.edu", grade: "10th", enrolledActivities: ["a1", "a4"], joinDate: "2024-09-01" },
  { id: "s2", name: "Liam Johnson", email: "liam.j@school.edu", grade: "11th", enrolledActivities: ["a2", "a6"], joinDate: "2023-09-01" },
  { id: "s3", name: "Sophia Martinez", email: "sophia.m@school.edu", grade: "9th", enrolledActivities: ["a3", "a5"], joinDate: "2025-09-01" },
  { id: "s4", name: "Noah Williams", email: "noah.w@school.edu", grade: "12th", enrolledActivities: ["a1", "a8"], joinDate: "2022-09-01" },
  { id: "s5", name: "Olivia Brown", email: "olivia.b@school.edu", grade: "10th", enrolledActivities: ["a4", "a6"], joinDate: "2024-09-01" },
  { id: "s6", name: "Ethan Davis", email: "ethan.d@school.edu", grade: "11th", enrolledActivities: ["a2", "a3"], joinDate: "2023-09-01" },
  { id: "s7", name: "Ava Taylor", email: "ava.t@school.edu", grade: "9th", enrolledActivities: ["a5", "a8"], joinDate: "2025-09-01" },
  { id: "s8", name: "Mason Anderson", email: "mason.a@school.edu", grade: "12th", enrolledActivities: ["a1", "a4", "a6"], joinDate: "2022-09-01" },
]

export const mockOrganizers = [
  { id: "t1", name: "James Wilson", email: "james.w@school.edu", department: "Physical Education", activitiesManaged: ["a1", "a5"] },
  { id: "t2", name: "Dr. Maria Lopez", email: "maria.l@school.edu", department: "Science", activitiesManaged: ["a2", "a6"] },
  { id: "t3", name: "Ms. Rachel Green", email: "rachel.g@school.edu", department: "Arts", activitiesManaged: ["a3", "a7"] },
  { id: "t4", name: "Prof. Alan Turing", email: "alan.t@school.edu", department: "Computer Science", activitiesManaged: ["a4", "a8"] },
]

export const mockAnnouncements = [
  {
    id: "an1",
    title: "Spring Activities Registration Open",
    content: "Registration for all spring semester activities is now open. Please sign up before March 10th to secure your spot.",
    author: "Sarah Chen",
    date: "2026-03-01",
    priority: "high",
  },
  {
    id: "an2",
    title: "Basketball Tournament Schedule Update",
    content: "The tournament has been rescheduled to March 15th due to facility maintenance. All registered participants will be notified.",
    author: "James Wilson",
    date: "2026-03-03",
    priority: "medium",
  },
  {
    id: "an3",
    title: "New Computer Lab Equipment",
    content: "The engineering lab has been upgraded with new 3D printers and robotics kits. Available for club use starting next week.",
    author: "Prof. Alan Turing",
    date: "2026-03-02",
    priority: "low",
  },
  {
    id: "an4",
    title: "Community Service Hours Reminder",
    content: "All students must complete a minimum of 20 community service hours per semester. Check available volunteer opportunities.",
    author: "Sarah Chen",
    date: "2026-02-28",
    priority: "medium",
  },
]
